In [1]:
import numpy as np


In [2]:
embedding_size =4
vocab_size = 10

embedding_matrix = np.arange(embedding_size * vocab_size, dtype='float32')
embedding_matrix = embedding_matrix.reshape(vocab_size, embedding_size)
print(embedding_matrix)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]
 [32. 33. 34. 35.]
 [36. 37. 38. 39.]]


In [3]:
i=3
print(embedding_matrix[i])

[12. 13. 14. 15.]


In [4]:
def onehot_encode(dim, label):
    return np.eye(dim)[label]

onehot_i = onehot_encode(vocab_size, i)
print(onehot_i)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [5]:
embedding_vector = np.dot(onehot_i, embedding_matrix)
print(embedding_vector)

[12. 13. 14. 15.]


In [6]:
from keras.layers import Embedding

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [7]:
embedding_layer = Embedding(
    output_dim=embedding_size,
    input_dim=vocab_size,
    weights = [embedding_matrix],
    input_length = 1,
    name = 'my_embedding'
)

In [8]:
from keras.layers import Input
from keras.models import Model

x = Input(shape=[1], name='input')
embedding = embedding_layer(x)
model = Model(inputs=x, outputs=embedding)


In [9]:
model.output_shape

(None, 1, 4)

In [10]:
model.get_weights()

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.],
        [32., 33., 34., 35.],
        [36., 37., 38., 39.]], dtype=float32)]

In [11]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           (None, 1)                 0         
_________________________________________________________________
my_embedding (Embedding)     (None, 1, 4)              40        
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [12]:
labels_to_encode = np.array([[3]])
model.predict(labels_to_encode)

array([[[12., 13., 14., 15.]]], dtype=float32)

In [13]:
labels_to_encode = np.array([[3],[3],[0],[9]])
model.predict(labels_to_encode)

array([[[12., 13., 14., 15.]],

       [[12., 13., 14., 15.]],

       [[ 0.,  1.,  2.,  3.]],

       [[36., 37., 38., 39.]]], dtype=float32)

In [14]:
from keras.layers import Flatten

In [15]:
x = Input(shape=[1], name='input')
y = Flatten()(embedding_layer(x))
model2 = Model(inputs=x, outputs=y)

In [16]:
model2.output_shape

(None, 4)

In [17]:
model2.predict(np.array([3]))

array([[12., 13., 14., 15.]], dtype=float32)

In [18]:
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           (None, 1)                 0         
_________________________________________________________________
my_embedding (Embedding)     (None, 1, 4)              40        
_________________________________________________________________
flatten_1 (Flatten)          (None, 4)                 0         
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [19]:
model2.set_weights([np.ones(shape=(vocab_size, embedding_size))])

In [20]:
labels_to_encode = np.array([[3]])
model2.predict(labels_to_encode)

array([[1., 1., 1., 1.]], dtype=float32)

In [21]:
model.predict(labels_to_encode)

array([[[1., 1., 1., 1.]]], dtype=float32)

In [22]:
from keras.models import Sequential

In [33]:
model3 = Sequential()

In [36]:
model3.add(embedding_layer)

In [37]:
model3.add(Flatten())

In [38]:
model3.predict(labels_to_encode)

array([[1., 1., 1., 1.]], dtype=float32)